Cache the Trivy database. Specify the exact filename to upload.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -10,6 +10,9 @@ on:
 jobs:
   build-and-push:
     runs-on: ubuntu-latest
+    
+    env:
+      TRIVY_CACHE_DIR: ~/.cache/trivy
 
     steps:
     - name: Checkout code
@@ -46,7 +49,12 @@ jobs:
             # Run Trivy scan
             echo "🛡️ Scanning $dir with Trivy..."
             REPORT_PATH="trivy-reports/$dir.sarif"
-            trivy image --format sarif --output $REPORT_PATH ${{ secrets.DOCKERHUB_USERNAME }}/$dir:latest || echo "Trivy scan failed for $dir"
+            trivy image \
+              --cache-dir "${TRIVY_CACHE_DIR}" \
+              --download-db-only \
+              --format sarif \
+              --output "$REPORT_PATH" \
+              $IMAGE_NAME:latest || echo "Trivy scan failed for $dir"            
             echo "Scanned $dir with Trivy success. Report saved at $REPORT_PATH"            
             cat $REPORT_PATH
             echo "Pushing image..."
@@ -61,4 +69,4 @@ jobs:
     - name: Upload Trivy SARIF reports to GitHub Security tab
       uses: github/codeql-action/upload-sarif@v3
       with:
-        sarif_file: trivy-reports/*.sarif
+        sarif_file: trivy-reports/backend.sarif
